name: GraphWalker Installer Tests

on: [push]

jobs:
  # test-ubuntu:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       graphwalker-version: [ 'latest', '4.3.1', '' ]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '11'
  #         distribution: 'adopt'
  #     - name: Install GraphWalker ${{ matrix.graphwalker-version }}
  #       run: |
  #         chmod +x install-graphwalker.sh
  #         ./install-graphwalker.sh ${{ matrix.graphwalker-version }}
  #     - name: Run GraphWalker
  #       run: |
  #         gw --version

  # test-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '11'
  #         distribution: 'adopt'
  #     - name: Install GraphWalker
  #       run: |
  #         chmod +x install-graphwalker.sh
  #         ./install-graphwalker.sh
  #     - name: Run GraphWalker
  #       run: |
  #         gw --version

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install GraphWalker
        run: |
          ./install-graphwalker.bat
      - name: Run GraphWalker
        run: |
          gw --version
